version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: '123456'
      DATABASE_URL=postgres: username:postgres@db:15432/sequelize
    ports:
      - '15432:5432'
    networks:
      - databases

  # app:
  #   build: .
  #   command: yarn dev
  #   ports:
  #     - '3938:3938'
  #   volumes:
  #     - .:/usr/app

networks:
  databases:
    driver: bridge
