version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: '123456'
      DATABASE_URL=postgres: username:postgres@db:15432/sequelize
    ports:
      - '15432:5432'
    networks:
      - databases

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "5433:80"
    depends_on:
      - postgres
    networks:
      - databases

  app:
    build: .
    command: yarn dev
    ports:
      - '3938:3938'
    volumes:
      - .:/usr/app

networks:
  databases:
    driver: bridge
